# Generated by Django 4.0.2 on 2022-06-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='status',
            field=models.CharField(default='request pending', max_length=100),
        ),
    ]
