# Generated by Django 4.0.2 on 2022-06-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_remove_add_status_requst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requst',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
