# Generated by Django 4.0.2 on 2022-06-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_alter_requst_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requst',
            name='z',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
